# Generated by Django 5.2.16 on 2026-07-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('scene_number',),
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='projects.project')),
            ],
            options={
                'ordering': ('act_number',),
                'unique_together': {('project', 'act_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to open'), ('open', 'Open'), ('satisfied', 'Satisfied'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('claim_mode', models.CharField(choices=[('single', 'One contributor'), ('open_call', 'Open call')], default='single', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='production.scene')),
            ],
            options={
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('script', 'Script'), ('character', 'Character reference'), ('wardrobe', 'Wardrobe reference'), ('set', 'Set reference'), ('prop', 'Prop reference'), ('video', 'Video'), ('audio', 'Audio'), ('music', 'Music'), ('document', 'Document')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('external_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under review'), ('approved', 'Approved'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_resources', to='projects.membership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('sequence_rules', models.TextField(blank=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='production.act')),
            ],
            options={
                'ordering': ('sequence_number',),
                'unique_together': {('act', 'sequence_number')},
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='production.sequence'),
        ),
        migrations.CreateModel(
            name='TaskClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('released', 'Released')], default='active', max_length=20)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_claims', to='projects.membership')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='production.productiontask')),
            ],
        ),
        migrations.CreateModel(
            name='PacketSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('story', 'Story and action'), ('performance', 'Performance'), ('wardrobe', 'Wardrobe'), ('set', 'Set and props'), ('camera', 'Camera and lighting'), ('continuity', 'Continuity'), ('generation', 'Generation instructions'), ('final_prompt', 'External prompt')], max_length=30)),
                ('content', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Awaiting approval'), ('approved', 'Approved'), ('revision', 'Revision requested')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_packet_sections', to='projects.membership')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packet_sections', to='projects.department')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_sections', to='production.productiontask')),
            ],
            options={
                'unique_together': {('task', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='CharacterTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='characters.character')),
                ('character_identity_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='characters.characteridentityversion')),
                ('character_look', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='characters.characterlook')),
                ('character_scene_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='characters.characterscenestate')),
                ('performance_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='characters.performanceprofile')),
                ('voice_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='characters.voiceprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='production.productiontask')),
            ],
            options={
                'unique_together': {('task', 'character')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('sequence', 'scene_number')},
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='production.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='production.productiontask')),
            ],
            options={
                'unique_together': {('task', 'resource')},
            },
        ),
    ]
