# Generated by Django 5.2.16 on 2026-07-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
        ('production', '0001_initial'),
        ('projects', '0003_membership_public_credit_opt_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_script_documents', to='projects.membership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_documents', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('raw_text', models.TextField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_script_versions', to='projects.membership')),
                ('script_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='production.scriptdocument')),
            ],
            options={
                'ordering': ('-version_number',),
                'unique_together': {('script_document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ScriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.PositiveIntegerField()),
                ('segment_type', models.CharField(choices=[('scene_heading', 'Scene Heading'), ('action', 'Action'), ('dialogue', 'Dialogue'), ('parenthetical', 'Parenthetical'), ('transition', 'Transition'), ('paragraph', 'Paragraph')], max_length=30)),
                ('text_content', models.TextField()),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_segments', to='characters.character')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_segments', to='production.scene')),
                ('script_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='production.scriptversion')),
            ],
            options={
                'ordering': ('segment_number',),
                'unique_together': {('script_version', 'segment_number')},
            },
        ),
        migrations.CreateModel(
            name='TaskScriptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_text_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ending_task_links', to='production.scriptsegment')),
                ('script_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='production.scriptversion')),
                ('start_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_task_links', to='production.scriptsegment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_links', to='production.productiontask')),
            ],
        ),
    ]
