# Generated by Django 5.2.16 on 2026-07-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
        ('production', '0002_scriptdocument_scriptversion_scriptsegment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptCharacterSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('raw_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('merged', 'Merged'), ('rejected', 'Rejected')], db_index=True, default='suggested', max_length=20)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_suggestions', to='characters.character')),
                ('script_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_suggestions', to='production.scriptversion')),
            ],
            options={
                'ordering': ('-occurrence_count', 'name'),
                'unique_together': {('script_version', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScriptCharacterMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_mentions', to='characters.character')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_mentions', to='production.scriptsegment')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='production.scriptcharactersuggestion')),
            ],
            options={
                'unique_together': {('suggestion', 'segment')},
            },
        ),
    ]
