# Generated by Django 5.2.16 on 2026-07-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
        ('production', '0003_scriptcharactersuggestion_scriptcharactermention'),
        ('projects', '0003_membership_public_credit_opt_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editorial_strategy', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('stale', 'Stale (Script Changed)'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_coverage_plans', to='projects.membership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_plans', to='projects.project')),
                ('script_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_plans', to='production.scriptversion')),
            ],
        ),
        migrations.CreateModel(
            name='CoveragePlanSegmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_snapshot', models.TextField()),
                ('coverage_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_links', to='production.coverageplan')),
                ('end_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ending_coverage_links', to='production.scriptsegment')),
                ('start_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_coverage_links', to='production.scriptsegment')),
            ],
        ),
        migrations.CreateModel(
            name='ShotDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('shot_category', models.CharField(choices=[('master', 'Master Shot'), ('wide', 'Wide Shot'), ('medium', 'Medium Shot'), ('close_up', 'Close-up'), ('extreme_close_up', 'Extreme Close-up'), ('ots', 'Over-the-Shoulder'), ('two_shot', 'Two-Shot'), ('reaction', 'Reaction Shot'), ('insert', 'Insert'), ('cutaway', 'Cutaway'), ('establishing', 'Establishing Shot'), ('transition', 'Transition Material'), ('b_roll', 'B-Roll'), ('pickup', 'Pickup'), ('alternate_take', 'Alternate Take'), ('effects_plate', 'VFX Plate'), ('clean_plate', 'Clean Plate')], default='medium', max_length=30)),
                ('editorial_purpose', models.TextField(blank=True)),
                ('framing_notes', models.TextField(blank=True)),
                ('camera_movement', models.CharField(blank=True, max_length=100)),
                ('lens_notes', models.CharField(blank=True, max_length=100)),
                ('duration_target_seconds', models.PositiveIntegerField(default=5)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='characters.character')),
                ('coverage_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='production.coverageplan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shots', to='projects.membership')),
            ],
            options={
                'ordering': ('sequence_order', 'shot_code'),
                'unique_together': {('coverage_plan', 'shot_code')},
            },
        ),
        migrations.CreateModel(
            name='EditorialWarningWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_code', models.CharField(max_length=80)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coverage_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_waivers', to='production.coverageplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_waivers', to='projects.project')),
                ('waived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waived_editorial_warnings', to='projects.membership')),
            ],
            options={
                'unique_together': {('coverage_plan', 'warning_code')},
            },
        ),
        migrations.CreateModel(
            name='ShotTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='production.shotdefinition')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_links', to='production.productiontask')),
            ],
            options={
                'unique_together': {('shot', 'task')},
            },
        ),
    ]
