# Generated by Django 5.2.16 on 2026-07-26 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('development', 'Development'), ('production', 'Production'), ('post', 'Post-production'), ('complete', 'Complete'), ('archived', 'Archived')], default='development', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('can_assign_tasks', models.BooleanField(default=False)),
                ('can_approve_department_work', models.BooleanField(default=False)),
                ('can_accept_final_assets', models.BooleanField(default=False)),
                ('can_manage_credits', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='projects.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credited_name', models.CharField(max_length=160)),
                ('public_handle', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('inactive', 'Inactive')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ProjectTermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('terms_text', models.TextField()),
                ('license_policy', models.TextField(blank=True)),
                ('credit_policy', models.TextField(blank=True)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_versions', to='projects.project')),
            ],
            options={
                'ordering': ('-version_number',),
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_department_head', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='projects.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='projects.productionrole')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('project', 'name')},
        ),
        migrations.CreateModel(
            name='MembershipAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='projects.membership')),
                ('terms_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_agreements', to='projects.projecttermsversion')),
            ],
            options={
                'unique_together': {('membership', 'terms_version')},
            },
        ),
    ]
