# Generated by Django 5.2.16 on 2026-07-26 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='available_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='membership',
            name='portfolio_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='membership',
            name='supported_asset_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='invited', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('development', 'Development'), ('production', 'Production'), ('post', 'Post-production'), ('complete', 'Complete'), ('archived', 'Archived')], db_index=True, default='development', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invites', to='projects.membership')),
                ('default_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invite_tokens', to='projects.productionrole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
