# Generated by Django 5.2.16 on 2026-07-26 19:46

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_membership_available_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='public_credit_opt_in',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='final_film_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='poster_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projectinvitetoken',
            name='token',
            field=models.CharField(db_index=True, default=apps.projects.models.generate_secure_invite_token, max_length=64, unique=True),
        ),
    ]
