# Generated by Django 5.2.16 on 2026-07-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_initial'),
        ('production', '0001_initial'),
        ('projects', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credited_name', models.CharField(max_length=160)),
                ('role_name', models.CharField(max_length=120)),
                ('department_name', models.CharField(max_length=120)),
                ('basis', models.CharField(choices=[('role', 'Production role'), ('resource', 'Approved resource'), ('responsibility', 'Creative responsibility / stewardship'), ('accepted_work', 'Accepted contribution'), ('final_cut', 'Used in final cut')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('eligible', 'Eligible'), ('confirmed', 'Confirmed'), ('withheld', 'Withheld')], default='pending', max_length=20)),
                ('contribution_summary', models.TextField(blank=True)),
                ('appears_in_screen_credits', models.BooleanField(default=True)),
                ('final_order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character_identity_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characteridentityversion')),
                ('character_look', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characterlook')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='projects.membership')),
                ('department_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.departmentreview')),
                ('packet_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.packetsection')),
                ('performance_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.performanceprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='projects.project')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.resource')),
                ('role_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.roleassignment')),
                ('submission_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.submissionversion')),
                ('voice_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.voiceprofile')),
            ],
        ),
    ]
