# Generated by Django 5.2.16 on 2026-07-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
        ('credits', '0001_initial'),
        ('production', '0001_initial'),
        ('projects', '0003_membership_public_credit_opt_in_and_more'),
        ('submissions', '0002_canonicalselection_unique_active_canonical_per_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditentry',
            name='appears_in_screen_credits',
        ),
        migrations.RemoveField(
            model_name='creditentry',
            name='final_order',
        ),
        migrations.RemoveField(
            model_name='creditentry',
            name='performance_profile',
        ),
        migrations.RemoveField(
            model_name='creditentry',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='creditentry',
            name='role_assignment',
        ),
        migrations.RemoveField(
            model_name='creditentry',
            name='voice_profile',
        ),
        migrations.AddField(
            model_name='creditentry',
            name='is_final_cut',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='basis',
            field=models.CharField(choices=[('role', 'Role assignment'), ('responsibility', 'Departmental responsibility'), ('accepted_work', 'Accepted work contribution'), ('director', 'Direction and creative authority')], max_length=30),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='character_identity_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='characters.characteridentityversion'),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='character_look',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='characters.characterlook'),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='department_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='submissions.departmentreview'),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='packet_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='production.packetsection'),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('eligible', 'Eligible'), ('verified', 'Verified'), ('rescinded', 'Rescinded')], db_index=True, default='eligible', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='submission_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='submissions.submissionversion'),
        ),
        migrations.CreateModel(
            name='ProjectProvenanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot_title', models.CharField(blank=True, max_length=200)),
                ('manifest_data', models.JSONField(default=dict)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_snapshots', to='projects.project')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_snapshots', to='projects.membership')),
            ],
            options={
                'ordering': ('-version_number',),
                'unique_together': {('project', 'version_number')},
            },
        ),
    ]
