# Generated by Django 5.2.16 on 2026-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_remove_creditentry_appears_in_screen_credits_and_more'),
        ('projects', '0003_membership_public_credit_opt_in_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectprovenancesnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='unique_snapshot_version_per_project'),
        ),
    ]
