# Generated by Django 5.2.16 on 2026-07-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('revision_requested', 'Revision requested'), ('accepted', 'Accepted'), ('alternate', 'Accepted as alternate'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='projects.membership')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='production.productiontask')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=500)),
                ('external_tool', models.CharField(blank=True, max_length=100)),
                ('prompt_used', models.TextField(blank=True)),
                ('seed', models.CharField(blank=True, max_length=100)),
                ('contributor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.membership')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='submissions.submission')),
            ],
            options={
                'ordering': ('version_number',),
                'unique_together': {('submission', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_authority', models.BooleanField(default=True)),
                ('external_tool', models.CharField(max_length=100)),
                ('commercial_use_allowed', models.BooleanField(default=True)),
                ('likeness_authorized', models.BooleanField(default=True)),
                ('source_asset_disclosure', models.TextField(blank=True)),
                ('attested_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='submissions.submissionversion')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('alternate', 'Accept as alternate'), ('revision', 'Request revision'), ('reject', 'Reject')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_reviews', to='projects.membership')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_reviews', to='submissions.submissionversion')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('issue_found', 'Issue found'), ('revision_recommended', 'Revision recommended'), ('not_applicable', 'Not applicable')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_reviews', to='projects.roleassignment')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_reviews', to='submissions.submissionversion')),
            ],
        ),
        migrations.CreateModel(
            name='CanonicalSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.membership')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_set', to='submissions.canonicalselection')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_selections', to='production.productiontask')),
                ('submission_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_uses', to='submissions.submissionversion')),
            ],
            options={
                'ordering': ('-selected_at',),
            },
        ),
    ]
