# Generated by Django 5.2.16 on 2026-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('projects', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='canonicalselection',
            constraint=models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('task',), name='unique_active_canonical_per_task'),
        ),
    ]
