# Generated by Django 5.2.16 on 2026-07-26 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_alter_auditevent_options_and_more'),
        ('projects', '0003_membership_public_credit_opt_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('missing_capability', 'Missing capability'), ('workflow_improvement', 'Workflow improvement'), ('confusing_interface', 'Confusing interface'), ('performance', 'Performance problem'), ('accessibility', 'Accessibility issue'), ('feature_request', 'Feature request'), ('other', 'Other')], default='workflow_improvement', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('what_user_was_doing', models.TextField()),
                ('actual_result', models.TextField(blank=True)),
                ('ideal_result', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low / Minor'), ('medium', 'Medium / Normal'), ('high', 'High / Important'), ('critical', 'Critical / Blocker')], default='medium', max_length=20)),
                ('page_url', models.CharField(max_length=500)),
                ('page_name', models.CharField(max_length=120)),
                ('context_type', models.CharField(blank=True, max_length=50)),
                ('context_identifier', models.CharField(blank=True, max_length=100)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('declined', 'Declined'), ('duplicate', 'Duplicate')], db_index=True, default='new', max_length=20)),
                ('github_issue_number', models.IntegerField(blank=True, null=True)),
                ('github_issue_url', models.URLField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.userfeedback')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='projects.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
