# Generated by Django 5.2.16 on 2026-07-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('emotional_range', models.TextField(blank=True)),
                ('movement_notes', models.TextField(blank=True)),
                ('mocap_reference_key', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('voice_actor_name', models.CharField(blank=True, max_length=160)),
                ('model_settings', models.JSONField(blank=True, default=dict)),
                ('sample_audio_key', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterIdentityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('facial_structure_notes', models.TextField(blank=True)),
                ('body_type', models.CharField(blank=True, max_length=160)),
                ('canonical_reference_image', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.membership')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_versions', to='characters.character')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='CharacterLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('wardrobe_description', models.TextField(blank=True)),
                ('costume_reference_images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='characters.character')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.membership')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterReferenceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('turnaround', 'Turnaround Sheet'), ('model_config', 'Model Config'), ('keyframe', 'Reference Keyframe'), ('expression', 'Expression Sheet')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('storage_key', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character_identity_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_assets', to='characters.characteridentityversion')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRightsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensor_name', models.CharField(max_length=200)),
                ('likeness_authorized', models.BooleanField(default=True)),
                ('voice_authorized', models.BooleanField(default=True)),
                ('model_training_allowed', models.BooleanField(default=False)),
                ('commercial_use_allowed', models.BooleanField(default=True)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('document_key', models.CharField(blank=True, max_length=500)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.membership')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_records', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSceneState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_notes', models.TextField(blank=True)),
                ('dirt_blood_level', models.CharField(blank=True, max_length=100)),
                ('wardrobe_damage', models.TextField(blank=True)),
                ('emotional_state', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_states', to='characters.character')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.membership')),
            ],
        ),
    ]
