# Generated by Django 5.2.16 on 2026-07-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('production', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterscenestate',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_states', to='production.scene'),
        ),
        migrations.AddField(
            model_name='performanceprofile',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profiles', to='characters.character'),
        ),
        migrations.AddField(
            model_name='performanceprofile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.membership'),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to='characters.character'),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.membership'),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='characteridentityversion',
            unique_together={('character', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='characterscenestate',
            unique_together={('character', 'scene')},
        ),
    ]
